export * from "./signup"
export * from "./email-verification"
export * from "./email-social"
export * from "./digiloger"
export * from "./personal-state-one";
export * from "./personal-state-two";
export * from "./nominee-add";
export * from "./nominee-fetch";
export * from "./validation";
export * from "./bank";